# -*- coding: utf-8 -*-
"""20230215_1_광운대.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BkOPyZPc3qYwWPBZ7V0b8mvTg1QPIf3a
"""

# factorial 함수 만들기

def fac(n):
    if n <= 1:
        return n
    else:
        return fac(n-1)*n

fac(5)

# 피보나치 수열 함수 만들기
a = 0
b = 1
count = 0
# 0, 1, 1, 2, 3, 5, 8, 13 ...

def fibo(n):
    # if n <= 1:
    #     return n
    global count  # memoegation 이유를 위함
    count += 1

    if n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        return fibo(n-2) + fibo(n-1)

count = 0
fibo(5)
count

alist = {1 : 0, 2 : 1}
count = 0
def fibo(n):
    global count
    count += 1
    if n in alist:
        return alist[n]
    
    alist[n] = fibo(n-2) + fibo(n-1)
    return alist[n]

fibo(100)
count