# -*- coding: utf-8 -*-
"""20230213_2_광운대.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arS2yBBZveN44H8KoC8wnAvKSN5pyJot
"""

box = [] # [1,2,3,4,5]

for i in range(1, 6):
    box.append(i)

box = [i for i in range(1, 11) if i % 2 == 0]
box

box = [(x, y, z) for x in ['x', 'y', 'z'] 
                for y in ['a', 'b', 'c']
                    for z in ['가서 먹기', '배달 시키기']]
box

[x for x in range(10) if x < 5 if x % 2 == 0]

# stack, queue

box = [1,2,3,4,5]

# 이진법 : 0과 1로 이루어진 값

t = "1010"
t = int(t, 2) #
t

bin(10)[2:]

# p.4 : 문자열 계산하기

t = 'print("Hello World")'
eval(t) # 이 문자열을 py 코드로 변환해줘

a = 'print(5 + 3)'
a = eval(a)
a

box = [[1, 3],[2, 3],[6, 5],[7,4],[9,2]]
box.sort(key=lambda x: (x[0],x[1]))

box