# -*- coding: utf-8 -*-
"""20230215_2_광운대.ipynb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SdSTHkABJYO3Inv5H6UaNYpX9q52skAs
"""

# 힙
import heapq

heap = []

heapq.heappush(heap, 45)
heapq.heappush(heap, 36)
heapq.heappush(heap, 54)
heapq.heappush(heap, 27)
heapq.heappush(heap, 63)

heap

heapq.heappop(heap)
heap

heapq.heappop(heap)
heap