# -*- coding: utf-8 -*-
"""20230213_1_광운대.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zZ956M_0BUXPzx-aCok1S0V7D2P0AnML
"""

# 복사

a = 5  # 손상입으면 안 되는 주요한 정보
b = a

b = 10
print(b, a)

a = [1,2,3]  # 중요한 정보
b = a

b[1] = 8
print(b, a)

a = [1,2,3]
b = a[:] # 복사의 의미

box = [1,2,3,4,5,6,7,8]
box[:5:2] # 증감 연산자로 사용할 수 있다..!

t = 'Hello World!'
t[::-1]

t = '54321'
t = [int(i) for i in t]
t

# filter, map, lambda, list_comp

def my_func(x):
    return x > 0

# filter(함수, 리스트)
box = [-1, 3, -2, 5, 0, 7]

list(filter(my_func, box)) # 변수 박스 안에 있는 모든 요소에 true 나온 값만 필터링

# lambda : 아주 간단한 함수를 만들 때 사용 함

def add(num1, num2):
    return num1 + num2

add(3, 4)

add = lambda num1, num2 : num1 + num2  # : 기준으로 input:output
add(5, 6)

box = [-1, 3, -2, 5, 0, 7]

list(filter(lambda x : x>0, box))

box = ['1','2','3','4','5']  #[1,2,3,4,5]로 바꾸고 싶음

list(map(int, box)) # 박스 안에 있는 모든 요소에 int를 적용한다.

