SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT S.USER_ID) USERS
FROM USER_INFO U RIGHT JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3